# Generated by Django 5.2.11 on 2026-04-24 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(default='Growing', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('READY', 'Ready'), ('HARVESTED', 'Harvested')], default='PLANTED', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Observations from the field agent')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'user_type': '2'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fields', to=settings.AUTH_USER_MODEL)),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_location', to='home.crop')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
